version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
    - ./src:/usr/share/nginx/html
    ports:
    - "4444:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
